services:
  - type: web
    name: sari-sari-utang-tracker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: USER_NAME
        sync: false
      - key: PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
